baseURL = 'https://afazzi-github-io.pages.dev/'
languageCode = 'en-us'
title = "Fazzi's Site"
theme = 'hello-friend-ng'

# Enable modern Hugo features
enableGitInfo = true
enableEmoji = true
enableRobotsTXT = true
enableFingerprinting = true
buildFuture = true

# Performance optimizations
minify = true
gc = true

# Content organization
summaryLength = 200

[pagination]
  pagerSize = 5

# Menu configuration
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

# Theme params
[params]
  description = "A personal blog built with Hugo"
  author = "Your Name"
  github = "afazzi"
  enableDarkMode = true
  enableSearch = true
  showReadingTime = true
  showToc = true
  tocOpen = true
  # hello-friend-ng supports customCSS list of URLs
  customCSS = ["/css/custom.css"]

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = true

# Security headers
[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$', '^git$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']