baseURL = 'https://blog.fazzi.me/'
languageCode = 'en-us'
title = "Fazzi's Site"
theme = 'hello-friend-ng'

# Enable modern Hugo features
enableGitInfo = false
enableEmoji = true
enableRobotsTXT = true
enableFingerprinting = true
buildFuture = true

# Performance optimizations
minify = true
gc = true

# Content organization
summaryLength = 200

enableThemeToggle = true
enableSharingButtons = true

#gitUrl = "https://github.com/afazzi/afazzi.github.io/"

[pagination]
  pagerSize = 5

# Menu configuration
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

# Theme params
[params]
  description = "An uninteresting website"
  author = "Fazzi"
  github = "afazzi"
  enableDarkMode = true
  enableSearch = true
  showReadingTime = true
  showToc = true
  tocOpen = true
  # hello-friend-ng supports customCSS list of URLs
  customCSS = ["/css/custom.css"]

[[params.social]]
  name = "steam"
  url = "https://steamcommunity.com/id/retsam"

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = true

# Security headers
[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$', '^git$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

[params.logo]
  logoMark     = ">"
  logoText     = "$ cd /home/"
  logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
  logoCursorDisabled = true
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"
    # Append the current url pathname to logoText 
  logoCursorPathname = true

[markup.goldmark.renderHooks.image]
enableDefault = true
[markup.goldmark.renderHooks.link]
enableDefault = true
