name: Build Hugo site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
          rsync -avz --delete . andrew@192.168.1.55:/home/andrew/quickstart/source

      - name: Build with Hugo on server
        run: |
          ssh andrew@192.168.1.55 'cd /home/andrew/quickstart/source && hugo --gc --minify'

      - name: Deploy to Server
        run: |
          ssh andrew@192.168.1.55 'rsync -avz --delete /home/andrew/quickstart/source/public/ /home/andrew/quickstart/public'
